library(data.table)
names(fread("household_power_consumption.txt"))
library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sql = "SELECT * FROM file WHERE Date = '1/2/2007' OR Date = '2/2/2007' ", sep = ";")
data$DateTime <- paste(data$Date, data$Time)
data$DateTime <- strptime(data$DateTime, format = "%d/%m/%Y %H:%M:%S")
png(file = "plot4.png", width = 480, height = 480)
par(mfrow = c(2,2), mar = c(4,4,1,1), oma = c(0,0,2,0))
with(data, {
        plot(DateTime, Global_active_power, xlab = "", ylab = "Global Active Power", type = "n")
        lines(DateTime, Global_active_power)
        plot(DateTime, Voltage, xlab = "datetime", ylab = "Voltage", type = "n")
        lines(DateTime, Voltage)
        plot(DateTime, Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
        lines(DateTime, Sub_metering_1, col = "Black")
        lines(DateTime, Sub_metering_2, col = "Red")
        lines(DateTime, Sub_metering_3, col = "Blue")
        legend("topright", lty = 1, col = c("Black", "Red", "Blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n", cex = 0.5)
        plot(DateTime, Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "n")
        lines(DateTime, Global_reactive_power)
}
)
dev.off()