library(data.table)
names(fread("household_power_consumption.txt"))
library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sql = "SELECT * FROM file WHERE Date = '1/2/2007' OR Date = '2/2/2007' ", sep = ";")
data$DateTime <- paste(data$Date, data$Time)
data$DateTime <- strptime(data$DateTime, format = "%d/%m/%Y %H:%M:%S")
png(file = "plot2.png", width = 480, height = 480)
plot(data$DateTime, data$Global_active_power, xlab = "", ylab = "Global Active Power(kilowatts)", type = "n")
lines(data$DateTime, data$Global_active_power)
dev.off()